services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_goods
    ports:
      - 5436:5432
    networks:
      - app-network

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh -c "/wait && /app/cmd/goods"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=20
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=20
    links:
      - postgres
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
