services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_goods
    expose:
      - 5432
    ports:
      - 5436:5432
    networks:
      - app-network

  app:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh -c "/wait && /app/cmd/goods"
    environment:
      - PORT=8001
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=my_goods
      - DB_HOST=postgres
      - DB_PORT=5432
      - SSL_MODE=disable
      - DEBUG=true

      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=20
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=20
    links:
      - postgres
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
