# DEFAULT CONF FILE. YOU SHOULD REDEFINE HERE YOUR LOCAL ENVIRONMENT VARS IF YOU PREFER TO USE THEM AS CONFIGS

port: "app_port"
db:
  host: "db_host"
  port: "db_port"
  name: "db_name"
  user: "db_user"
  pwd: "db_pass"
  sslMode: "ssl_mode"
